#!/usr/bin/env ruby
require 'shellwords'

BUILTINS = {
  'cd' => ->(dir = ENV["HOME"]) { Dir.chdir(dir) },
  'exit' => ->(code = 0){ exit(code.to_i) },
  'exec' => ->(*command) { exec *command }
}

def run(line)
  command, *arguments = Shellwords.shellsplit(line) 

  if BUILTINS[command]
    BUILTINS[command].call(*arguments)
  else
    pid = fork {
      exec line
    }

    Process.wait pid
  end
end

loop do
  $stdout.print "#{Dir.pwd} $ "
  k = $stdin.gets
  if k.nil?
    run "exit"
  else
    run k.strip
  end
end

